spring:
  jpa:
    hibernate:
      ddl-auto: none   # Overridden per profil
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: false
logging:
  level:
    root: INFO
    com.yourpackage: DEBUG
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  metrics:
    export:
      prometheus:
        enabled: true
